silver_stage:
  target: prod-silver
  outputs:
    prod-silver:
      type: clickhouse
      schema: prod-silver          # Your target database/schema
      host: dwh-db-clickhouse             # Or your hostname
      port: 8123
      user: admin
      password: 'admin123'                # Or your password
      secure: False               # Set to True if using HTTPS
      database: prod-silver        # Same as schema